name: online_exam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  flutter_native_splash: ^2.4.7

  # Network & Data
  dio: ^5.9.0
  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  logger: ^2.6.0

  # State Management & DI
  flutter_bloc: ^9.1.1
  get_it: ^7.7.0
  injectable: ^2.4.1
dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.6.0
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0
  injectable_generator: ^2.4.1

  # Lints
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
